[package]
name = "mal"
version = "0.1.0"
authors = ["abdullah <44318011+fx2y@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "5.0.5"
lazy_static = "1.4.0"
regex = "1.3.1"